stages:
  - build
  - test

Build:
  stage: build
  image: gradle:jdk17-alpine
  before_script:
    - echo `pwd`
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - gradle wrapper
    - ./gradlew assemble
    - ls
  artifacts:
    when: always
    paths:
      - build/libs/*.jar
    expire_in: 1 week

Test:
  stage: test
  image: gradle:jdk17-alpine
  dependencies:
    - Build
  services:
    - "postgres:latest"
  before_script:
    - echo `pwd`
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - export SPRING_PROFILES_ACTIVE=test
  script:
    - gradle check --info --stacktrace
    - gradle test
    - gradle jacocoTestReport
    - grep -Eo "Total.*?([0-9]{1,3})%" build/jacocoHtml/index.html
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
  coverage: '/Total.*?([0-9]{1,3})%/'