name: Continous Deployment (CD)

on:
  push:
  pull_request:


jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
    
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/a13heymartbalancekeranjangbelanjahistoryrating:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/a13heymartbalancekeranjangbelanjahistoryrating:latest

      - name: Deploy
        run: |
          gcloud run deploy booku-be-booklist \
          --region europe-west1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/a13heymartbalancekeranjangbelanjahistoryrating \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
