name: "Sonarcloud Scanning"

on:
  pull_request:
    branches:
      - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
            with:
                    fetch-depth: 0
        -   name: SonarCloud Scan
            uses: sonarsource/sonarcloud-github-action@master
            env:
                GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            with:
                args: >
                    -Dsonar.organization=advpro-2024-a13
                    -Dsonar.projectKey=Food-Groceries-Balance-KeranjangBelanja-HistoryRating
