name: "Sonarcloud Scanning"

on:
  pull_request:
    branches:
      - dev
      - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
            with:
                    fetch-depth: 0
        -   name: Set up JDK 21
            uses: actions/setup-java@v3
            with:
                distribution: 'temurin'
                java-version: '21'
        -   name: Make ./gradlew executable
            run: chmod +x ./gradlew
        -   name: Build with Gradle
            run: ./gradlew build
        -   name: SonarCloud Scan
            uses: sonarsource/sonarcloud-github-action@master
            env:
                GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            with:
                args: >
                    -Dsonar.organization=advpro-2024-a13
                    -Dsonar.projectKey=advpro-2024-a13_Food-Groceries-Balance-KeranjangBelanja-HistoryRating
                    -Dsonar.java.binaries=build/classes/java/main/heymart/backend/*.class,build/classes/java/main/heymart/backend/models/*.class,build/classes/java/main/heymart/backend/controller/*.class,build/classes/java/main/heymart/backend/repository/*.class,build/classes/java/main/heymart/backend/service/*.class,build/classes/java/main/heymart/backend/enums/*.class
                    -Dsonar.java.libraries=build/libs/*.jar
                    -Dsonar.gradle.skipCompile=true
                    -Dsonar.java.test.binaries=build/classes/java/test/heymart/backend/*.class,build/classes/java/test/heymart/backend/models/*.class,build/classes/java/test/heymart/backend/controller/*.class,build/classes/java/test/heymart/backend/repository/*.class,build/classes/java/test/heymart/backend/service/*.class,build/classes/java/test/heymart/backend/enums/*.class
                    -Dsonar.junit.reportPaths=build/test-results/test/*.xml
                    -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
